name: Keep Backend Alive

on:
  schedule:
    - cron: "*3/ * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping backend
        run: |
          echo "Checking backend..."

          response=$(curl -L -s -o /dev/null -w "%{http_code}" "https://divinesky-613l.onrender.com/health")

          echo "HTTP Status: $response"

          if [ "$response" -ne 200 ]; then
            echo "Backend not responding properly ❌"
            exit 1
          fi

          echo "Backend is alive ✅"
